require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'gcsusmobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'gcsusmobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
end

target 'gcsusmobile-tvOS' do
  # Pods for gcsusmobile-tvOS

  target 'gcsusmobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
